# Yarn 4 Global Configuration
# Use classic node_modules structure for compatibility (Cloudflare Workers, etc.)
nodeLinker: node-modules

# Faster installs with compression
compressionLevel: mixed

# Enable global cache to share packages across projects
enableGlobalCache: true
