curl.cainfo=/Users/niclaskahlmeier/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/niclaskahlmeier/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0

memory_limit=2048M
upload_max_filesize=10M
auto_prepend_file=/Applications/Herd.app/Contents/Resources/valet/dump-loader.php
extension=/Applications/Herd.app/Contents/Resources/herd-ext/herd-74-arm64.so
post_max_size=10M