curl.cainfo=/Users/niclaskahlmeier/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/niclaskahlmeier/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0
output_buffering=4096

auto_prepend_file=/Applications/Herd.app/Contents/Resources/valet/dump-loader.php
extension=/Applications/Herd.app/Contents/Resources/herd-ext/herd-84-arm64.so
memory_limit=2048M
upload_max_filesize=10M
post_max_size=10M